### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by sbowma15**
Simple Demo of JPanel in JPanel with proposed brutish button functionality toggling visibility. Will add to this to make strategy integration more understandable with current button functions. The idea is to keep everything in one GUI window. Its important to note, when a JPanelX is in JPanelY, setting JPanelY visibility to false makes JPanelX invisible also. A work around is to place all JPanels in same location instead of inside eachother. Otherwise, the component visibility of JPanelY should be toggled instead.

### CODE REVIEW

**Review by layer8sudostate — APPROVED** [review]
The code looks good. Have not run it yet though.

**Comment by Lfickling** [comment]
Shane We replaced the main with a version wrapped in Gradle. I recommend copying the changes you made, getting the most recent master and then readding in your changes and re-commiting and putting in a new pull request. sorry for the inconvenience.

**Comment by sbowma15** [comment]
Thanks, no worries.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Lfickling** [comment]
Shane, Does this mean I can close this pull request?

**Comment by sbowma15** [comment]
Yes 👍

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Pull request closed without merging**
