### PR TITLE
Lettie work on lookup

### LINKED ISSUE #27: website - allow customers to lookup inventory
create inventory.php (accessible from both index.html & userhome.html) that displays the inventory from the main table (produce id, quantity in stock, salesprice)

### PR DESCRIPTION
**Pull request by Lfickling**
derek, jesse and I got the lookup.php page to work. it displays past user data.

we still need to: add a 'cancel order' column to the sales_orders tables. get that working as a button option, make it so they can only order items we have in stock.

I also fixed some small formatting things like broken links and image sizing.

closes #27

### CODE REVIEW

**Review by jgonzo3224 — DISMISSED** [review]
looks good. Deleted some old code that was not needed becasue of new files that replaced the connection. Lookup code was finally figured out to display the results of a query on the database.

**Comment by DARhine** [comment]
Looks good

**Review by DARhine — DISMISSED** [review]
Changes look good!

**Comment by sbowma15** [comment]
Good changes

**Review by sbowma15 — APPROVED** [review]
Looks good to me !

**Review by DARhine — APPROVED** [review]
Still looks good!

**Review by DARhine — APPROVED** [review]
Second try to approve

**Review by DARhine — APPROVED** [review]
Second try to approve

**Pull request merged**
