### PR TITLE
form database connection

### PR DESCRIPTION
**Pull request by Lfickling**
the form now connects to the database and displays a thank you message with the details of your order.
in order to demo on your local, connect to this branch is vs-code. in your terminal navigate to the folder where the static files are.
enter: php -S 127.0.0.1:8080
in your browser go to: http://127.0.0.1:8080/index.html
click orderform
enter your order
it should show you the thank you message and the details of your order.
if you go into the database you will see your order on the sales_orders sheet
after you are done testing, don't forget to do control-C in your terminal to close the local php

### CODE REVIEW

**Review by jgonzo3224 — APPROVED** [review]
Looks good. The code was fixed to allow the website to connect to the database with the localhost as well as pages added in for login and lookup, as well as their connections. Also looks like another column was added to the CSS  format for the table.

**Review by sbowma15 — COMMENTED** [review]
looks good to me

**Review by sbowma15 — COMMENTED** [review]
nice

**Review by sbowma15 — COMMENTED** [review]
looks good

**Review by sbowma15 — COMMENTED** [review]
excellent

**Review by DARhine — APPROVED** [review]
Looks good.

**Review by jgonzo3224 — APPROVED** [review]
approving for merge

**Review by NoelC9 — APPROVED** [review]
Code looks good.

**Pull request merged**
